apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
kubernetesVersion: "v1.10.5"
imageRepository: registry.cn-hangzhou.aliyuncs.com/k10
networking:
  podSubnet: 172.20.0.0/16
  serviceSubnet: 172.21.0.0/16
kubeProxy:
  config:
    mode: "ipvs"
    featureGates: 
      SupportIPVSProxyMode: true
    clusterCIDR: 172.21.0.0/16
apiServerCertSANs:
featureGates:
  CoreDNS: true
